-- Retail Intelligence Platform - schema setup

-- 1) Database (optional but recommended)
CREATE DATABASE IF NOT EXISTS RETAIL_INTELLIGENCE;

-- 2) Schemas (layers)
CREATE SCHEMA IF NOT EXISTS RETAIL_INTELLIGENCE.STAGING;
CREATE SCHEMA IF NOT EXISTS RETAIL_INTELLIGENCE.WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS RETAIL_INTELLIGENCE.MARTS;

-- 3) Optional: a scratch/dev schema for ad-hoc work
CREATE SCHEMA IF NOT EXISTS RETAIL_INTELLIGENCE.SANDBOX;

